name: Android CI

on:
  workflow_dispatch:
  
permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: ./gradlew qa --parallel
      
    - run: ls -R app/build/outputs

    - name: Archive reports for failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: '*/build/reports'
